### ISSUE TITLE
1.ระบบล็อกอิน และ ยืนยันตัวตน

### ISSUE THREAD

**Issue by PP2546** [PP2546/PROJECT-COM-PRO#4]

**Comment by PP2546** [comment]
#include<iostream>
#include<fstream>
#include<string>
#include<cstdlib>

using namespace std;

bool login ()
{
    string username , password , name , pw ;

    cout << "Enter username" ; cin >> username ;
    cout << "Enter password" ; cin >> password ;

    ifstream read;
    read.open("data\\" + username + ".txt");
    getline(read,name);
    getline(read,pw);

    if(name == username && pw == password)
    {
        return true;
    }else{
        return false;
    }
}

int main()
{
    int c;

    cout << "HI , CUSTOMER\n" ;
    cout << "1:Register\t2:Login\nYour answer:" ; cin >> c ;
    
    if(c == 1)
    {
        string username , password;

        cout << "WHAT IS YOUR NAME? : " ;
        cin >> username;
        cout << "WHAT IS YOUR PASSWORD? : " ;
        cin >> password;

        ofstream dest;
        dest.open("data\\" + username + ".txt") ;
        dest << username << endl << password ;
        dest.close();

        main();
    }else if(c == 2){
        bool status = login() ;

        if(!status)
        {
            cout << "False Login" << endl ;
            system("PAUSE") ;
            return 0 ;
        }else{
            cout << "SUCCESS!!!" << endl ;
            system("PAUSE") ;
            return 1 ;
        }
    }
}

**Comment by PP2546** [comment]
ระบบยืนยันตัวตน.cpp

**Comment by PP2546** [comment]
https://github.com/PP2546/PROJECT-COM-PRO/blob/00cc8470bf7d90414cf9bbca6f9c29ebf5e90d10/ระบบยืนยันตัวตน

**Comment by SUPATKN** [comment]
https://youtu.be/m1uPsXeDp-Q เอาไปดูน้องๆ

**Comment by PP2546** [comment]
LOGIN และ REGISTER ตอนนี้เสร็จแล้วนะ สามารถใช้ CODE แยกใน login2.cpp นะ
ส่วน CODE เต็มอยู่ใน test1.cpp
